sonar.projectKey=mahimabinoj_lms-frontend
sonar.organization=mahimabinoj
sonar.sources=frontend-react/src
sonar.host.url=https://sonarcloud.io
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
