name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-react # This tells GitHub where your package.json is
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      # Add your SonarCloud and Snyk steps below this

      - name: Run tests
        run: npm test -- --passWithNoTests

    # TASK 4: SNYK Integration (Dependency Scan for Node.js)
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # Add this so SonarCloud runs even if Snyk finds bugs
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=frontend-react/package.json

      # TASK 3: SonarCloud Integration
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=.

    
        
